const User = require("./schema/User.schema");

/**
 * Finds the User by ID and deletes the user from the database
 * @param {String} id - Unique ID generated by MongoDB 
 * @returns deleteStatus else throws error from Mongodb
 */
const deleteUser = async (id) => {
    try {
        const deleteStatus = await User.findByIdAndDelete(id);
        return deleteStatus;
    } catch (error) { 
        throw error;
    }
}

module.exports = deleteUser;