const User = require("./schema/User.schema");

/**
 * The Edited user is updated by finding the user by ID and updating the database
 * @param {String} id - Unique ID generated by MongoDB 
 * @param {Object} content - The information that is edited by the user
 * @returns editStatus else throws error from Mongodb
 */
const editUser = async (id, content) => {
    try {
        let editStatus = await User.findByIdAndUpdate(id, content);
        return editStatus
    } catch(error) {
        throw error;
    }
}


module.exports = editUser;